# Generated by Django 4.1 on 2024-04-16 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion_residencia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_cargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuarios.cargo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario_cargos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona', to='modulo_usuarios.persona'),
        ),
    ]
