# Generated by Django 4.1 on 2024-04-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0004_alter_persona_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
