# Generated by Django 4.1 on 2024-05-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuarios', '0005_alter_persona_tipo_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField()),
                ('notas_voz', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'avance',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('usuarios_asignados', models.CharField(max_length=50)),
                ('id_usuario_capataz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('usuarios_asignados', models.CharField(max_length=50)),
                ('id_avance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.avance')),
                ('id_obra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.obra')),
                ('id_usuario_capataz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuarios.persona')),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='Persona_tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_tarea', to='modulo_usuarios.persona')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.tarea')),
            ],
            options={
                'db_table': 'persona_tarea',
            },
        ),
        migrations.CreateModel(
            name='Persona_obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.obra')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_obra', to='modulo_usuarios.persona')),
            ],
            options={
                'db_table': 'persona_obra',
            },
        ),
    ]
