# Generated by Django 4.1 on 2024-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tareas', '0002_obra_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
