# Generated by Django 4.1 on 2024-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tareas', '0004_tarea_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='nit',
            field=models.CharField(default='NIT', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='nit_number',
            field=models.CharField(default='Sin NIT', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='pais',
            field=models.CharField(default='Sin país', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='proveedores',
            field=models.CharField(default='Sin proveedores', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_pago',
            field=models.CharField(default='Sin pago', max_length=50),
        ),
    ]
