# Generated by Django 4.1 on 2024-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tareas', '0005_obra_direccion_obra_nit_obra_nit_number_obra_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='mes_inicio',
            field=models.CharField(default='Sin mes de inicio', max_length=50),
        ),
    ]
