# Generated by Django 4.1 on 2024-06-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0005_alter_persona_tipo_identificacion'),
        ('modulo_tareas', '0006_obra_mes_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='id_usuario_encargado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_encargado', to='modulo_usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='id_usuario_capataz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_capataz', to='modulo_usuarios.persona'),
        ),
    ]
