# Generated by Django 4.1 on 2024-06-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0005_alter_persona_tipo_identificacion'),
        ('modulo_tareas', '0007_obra_id_usuario_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='id_usuario_encargado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_encargado', to='modulo_usuarios.persona'),
        ),
    ]
