# Generated by Django 4.1 on 2024-06-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tareas', '0008_alter_obra_id_usuario_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra_avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.avance')),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_tareas.obra')),
            ],
            options={
                'db_table': 'obra_avance',
            },
        ),
    ]
